### ISSUE TITLE
Doesn't work for png images with alpha

### ISSUE THREAD

**Issue by shadowfox87** [AaronFeng753/Waifu2x-Extension-GUI#156] opened 2020-08-31 20:11 UTC
Hello,

I tried processing this image. It contains alpha as you can see.
![35699](https://user-images.githubusercontent.com/12994748/91763904-50bdc780-eba4-11ea-8150-bf21b90864b1.png)

Here are my settings for the engine:
![image](https://user-images.githubusercontent.com/12994748/91763936-63d09780-eba4-11ea-909a-3d63a13aeaae.png)

I want to only denoise this image rather than resize it.
![image](https://user-images.githubusercontent.com/12994748/91763948-69c67880-eba4-11ea-91b5-098533dac3b2.png)

![image](https://user-images.githubusercontent.com/12994748/91764002-84005680-eba4-11ea-8eb7-610ef661c3a5.png)

No matter what I do, the output always produce an image with a black background:
![35699_waifu2x_256x256_3n_png](https://user-images.githubusercontent.com/12994748/91764025-8f538200-eba4-11ea-8afc-5ac58eb412bb.png)

The denoise was successful but the alpha was not kept.

**Comment by shadowfox87** [comment] 2020-08-31 20:18
It seems that changing the image engine to waifu2x-caffe instead of ncnn-vulkan, it worked.

**Comment by AaronFeng753** [comment] 2020-08-31 22:58
This bug is caused by NCNN-Vulkan series engines.
It seems they can't keep the alpha channel of this particular image(other image works fine).
So this is a bug I can't fix by myself....

**Comment by AaronFeng753** [comment] 2020-08-31 23:08
I just create an issue for this bug: https://github.com/nihui/waifu2x-ncnn-vulkan/issues/107
And I'm gonna close this issue because I can't fix it....

**Comment by AaronFeng753** [comment] 2020-11-20 07:34
I just found a way to fix this, I'm working on it right now

**Comment by AaronFeng753** [comment] 2020-11-20 08:14
Fixed !!, gonna release a new beta version soon.
![test_alpha_W2xEX_PPAC_waifu2x_2x_4n_png](https://user-images.githubusercontent.com/52553688/99776209-64e1e700-2b4b-11eb-9994-ae698b191169.png)
![Snipaste_2020-11-20_16-14-26](https://user-images.githubusercontent.com/52553688/99776252-7aefa780-2b4b-11eb-9a18-14363c4b7163.jpg)

**Closed by AaronFeng753** 2020-11-20 08:14 UTC
Labels: bug

**Comment by AaronFeng753** [comment] 2020-11-20 10:45
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.57.13-beta
