### ISSUE TITLE
[BUG] keep subtitle mkv feature causes output to be malformed

### ISSUE THREAD

**Issue by Snazzie** [AaronFeng753/Waifu2x-Extension-GUI#433] opened 2022-10-19 15:43 UTC
**Software Version**
Latest BETA or Latest Stable?
v3.95.23-Premium

**Describe the bug**
enabling keep mkv subtitles feature causes output to be malformed/broken

#### in vlc
video stays black with vlc logo unless manually scrub to a different time..
when scrubbed back to start, image shows but is still and doesnt actually play images, just audio.

#### in windows media player
video starts without problem.  but trying to play any timestamp where audio is missing, it would immediately skip to next part where audio exists.

#### in both vlc and windows media player
large portion of audio is missing in the center.

**How to Reproduce the bug**
Steps to reproduce the bug:

sourcefile: 27 minute long mkv
segment: 40 sec
model: RealESRGAN  animev3
tilesize: 400   
2D
custom resolution: 1920x1080
2x scale
keep subtitles mkv
nvidia x265 encoding
nvidia decoder
1. enable keep mkv subtitle feature
1. upscale and render
2. play output video. 

**Expected behavior**
output is not malformed if keep subtitles is enabled

**Screenshots**

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

[link removed]

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

[VideoConfiguration_[Kayoanime] Domestic Na Kanojo S01E01_mkv_Waifu2xEX.ini.md](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/9821988/VideoConfiguration_.Kayoanime.Domestic.Na.Kanojo.S01E01_mkv_Waifu2xEX.ini.md)

**Desktop (please complete the following information):**
 - OS: windows 11
 - GPU Model RTX 3080Ti
 - CPU Model ryzen9 7950x
 - Amount of RAM: 64GB
 - Amount of VRAM: 12GB
 - Amount of Storage: 2TB

**Additional context**
VLC player
small 1 minute samples arent having this problem

**Comment by Snazzie** [comment] 2022-10-19 17:44
Looking at the post w2x clips. there arent any issues.
i think the issue only exists when stitching them together

**Comment by Snazzie** [comment] 2022-10-19 17:46
![image](https://user-images.githubusercontent.com/19627023/196766385-8cea9844-4a18-41d0-9866-dcb4950f440a.png)


if i dont scrub, it stays black

**Comment by Snazzie** [comment] 2022-10-19 17:48
Issue can be closed, if you dont think theres anything to be done here

**Comment by Snazzie** [comment] 2022-10-19 17:53
discovered another crazy bug in windows media player.
clicking anywhere where there isnt audio causes the playback position to fast forward to next place audio is available.
Slightly related to  https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/434

https://media.giphy.com/media/3mry6BoxhRbOfubsTb/giphy.gif

**Comment by Snazzie** [comment] 2022-10-19 18:16
i think its safe to say the encoded mkv output is malformed

**Comment by Snazzie** [comment] 2022-10-19 18:21
surprisingly, playing the video in avidemux is perfectly fine. both audio and video

**Comment by Snazzie** [comment] 2022-10-19 18:23
if i export again through avidemux, completely copying everything without modification.  video and audio playback is perfect.

**Comment by Snazzie** [comment] 2022-10-19 18:25
however the subtitles are dropped, when re exporting through avidemux. not sure if that plays any role to this bug?

**Comment by Snazzie** [comment] 2022-10-19 18:26
subtitles include blueray's format where you have translated signs and texts

**Comment by Snazzie** [comment] 2022-10-19 18:30
I re-processed the mkv this time without subtitle transfer being ticked. output is perfect.

So the problem is with the mkv subtitle feature

**Comment by Snazzie** [comment] 2022-10-19 18:39
updated issue from new discovery

**Comment by AaronFeng753** [comment] 2022-10-19 22:13
I need the original (source) video file to test this

This issue will remain closed until I received the original video file

**Comment by Snazzie** [comment] 2022-10-19 22:58
https://mega.nz/folder/2MU0QDbb#rmJqGYyuNo1tkjh6DxeQnA/file/qVlVHSAS

**Comment by Snazzie** [comment] 2022-10-19 23:00
@AaronFeng753 you can download it from that link

**Comment by AaronFeng753** [comment] 2022-10-20 03:01
Okay, it's now fixed!✅ Thank you for reporting this bug! Please wait for the next update!

**Comment by AaronFeng753** [comment] 2022-10-23 16:12
After take a more closer look at this issue, I found out that all of these weird issues were caused by the subtitle codec: pgs, which is not fully supported by ffmpeg (and avidemux, that's why `the subtitles are dropped, when re exporting through avidemux`)

**Closed by AaronFeng753** 2022-10-23 16:12 UTC
Labels: wontfix

**Comment by AaronFeng753** [comment] 2022-12-25 01:19
Issues #446 is deleted because it's not a bug report or an actual feature request, and even though this issue(#433) is closed but it's still on my to-do list, I will keep you informed by reply here if there are new developments about this issue in the future.
